FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY src/node/go.mod src/node/go.sum ./
RUN go mod download
COPY src/node/ .
COPY src/pkg/ /app/src/pkg/
RUN go build -o emdexer-node main.go

FROM alpine:latest
WORKDIR /app
RUN apk add --no-cache curl
COPY --from=builder /app/emdexer-node .
CMD ["./emdexer-node"]
