apiVersion: v1
kind: Secret
metadata:
  name: {{ include "emdexer-node.fullname" . }}-secret
type: Opaque
data:
  google-api-key: {{ .Values.secret.googleApiKey | b64enc | quote }}
  {{- if .Values.secret.openaiApiKey }}
  openai-api-key: {{ .Values.secret.openaiApiKey | b64enc | quote }}
  {{- end }}
