package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/piotrlaczykowski/emdexer/ui"
)

// cmdInit prompts for configuration values and writes a .env file.
func cmdInit() {
	fmt.Printf("\n  %s  %s\n\n", "🚀", ui.Bold("Emdexer Project Init"))

	scanner := bufio.NewScanner(os.Stdin)

	defaults := map[string]string{
		"GOOGLE_API_KEY":        "",
		"QDRANT_HOST":           "qdrant-1:6334",
		"EMDEX_NAMESPACE":       "default",
		"EMDEX_AUTH_KEY":        "",
		"EMDEX_GEMINI_MODEL":    "gemini-embedding-2-preview",
		"EMDEX_STREAM_ENABLED":  "true",
	}

	prompts := []struct {
		key          string
		label        string
		defaultValue string
	}{
		{"GOOGLE_API_KEY", "Google API Key", defaults["GOOGLE_API_KEY"]},
		{"QDRANT_HOST", "Qdrant host:port", defaults["QDRANT_HOST"]},
		{"EMDEX_NAMESPACE", "Default namespace", defaults["EMDEX_NAMESPACE"]},
		{"EMDEX_AUTH_KEY", "Auth key (empty for none)", defaults["EMDEX_AUTH_KEY"]},
		{"EMDEX_GEMINI_MODEL", "Gemini embedding model", defaults["EMDEX_GEMINI_MODEL"]},
		{"EMDEX_STREAM_ENABLED", "Enable LLM token streaming (true/false)", defaults["EMDEX_STREAM_ENABLED"]},
	}

	if _, err := os.Stat(".env"); err == nil {
		fmt.Printf("  %s %s\n\n", "⚠️", ui.Yellow(".env already exists and will be overwritten."))
	}

	values := make(map[string]string)
	for _, p := range prompts {
		if p.defaultValue != "" {
			fmt.Printf("  %s %s: ", ui.Cyan(p.label), ui.Dim("["+p.defaultValue+"]"))
		} else {
			fmt.Printf("  %s: ", ui.Cyan(p.label))
		}

		var input string
		if scanner.Scan() {
			input = strings.TrimSpace(scanner.Text())
		}
		if input == "" {
			input = p.defaultValue
		}
		values[p.key] = input
	}

	var sb strings.Builder
	sb.WriteString("# Emdexer configuration — generated by emdex init\n")
	for _, p := range prompts {
		sb.WriteString(fmt.Sprintf("%s=%s\n", p.key, values[p.key]))
	}

	if err := os.WriteFile(".env", []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "  %s %s: %v\n", "❌", ui.Red("Error writing .env"), err)
		os.Exit(1)
	}
	fmt.Printf("\n  %s %s\n", "✅", ui.Green("Wrote .env — run 'emdex start' to launch services."))
	fmt.Println()
}
