package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/piotrlaczykowski/emdexer/ui"
	"github.com/piotrlaczykowski/emdexer/version"
)

func main() {
	if len(os.Args) > 1 && os.Args[1][0] != '-' {
		switch os.Args[1] {
		case "init":
			cmdInit()
		case "start":
			cmdStart()
		case "status":
			cmdStatus()
		case "nodes":
			cmdNodes()
		default:
			fmt.Fprintf(os.Stderr, "\n  %s %s: %s\n", "❌", ui.Red("Unknown command"), os.Args[1])
			printUsage()
			os.Exit(1)
		}
		return
	}

	showVersion := flag.Bool("version", false, "show version")
	flag.Parse()

	if *showVersion {
		fmt.Printf("emdex version %s\n", version.Version)
		os.Exit(0)
	}

	printUsage()
}

func printUsage() {
	fmt.Println()
	fmt.Printf("  %s  %s\n", ui.Bold("📦 Emdexer CLI"), ui.Dim("v"+version.Version))
	fmt.Println()
	fmt.Printf("  %s emdex <command>\n", ui.Dim("Usage:"))
	fmt.Println()
	fmt.Printf("  %s\n", ui.Bold("Commands:"))
	fmt.Printf("    %s      Initialize a new emdexer project (.env)\n", ui.Cyan("init"))
	fmt.Printf("    %s     Start emdexer services via Docker Compose\n", ui.Cyan("start"))
	fmt.Printf("    %s    Show status of emdexer services\n", ui.Cyan("status"))
	fmt.Printf("    %s     List registered nodes and their status\n", ui.Cyan("nodes"))
	fmt.Println()
	fmt.Printf("  %s\n", ui.Bold("Flags:"))
	fmt.Printf("    %s  Show version information\n", ui.Cyan("--version"))
	fmt.Println()
}

// cmdInit prompts for configuration values and writes a .env file.
func cmdInit() {
	fmt.Printf("\n  %s  %s\n\n", "🚀", ui.Bold("Emdexer Project Init"))

	scanner := bufio.NewScanner(os.Stdin)

	defaults := map[string]string{
		"GOOGLE_API_KEY":     "",
		"QDRANT_HOST":        "qdrant-1:6334",
		"EMDEX_NAMESPACE":    "default",
		"EMDEX_AUTH_KEY":     "",
		"EMDEX_GEMINI_MODEL": "gemini-embedding-2-preview",
	}

	prompts := []struct {
		key          string
		label        string
		defaultValue string
	}{
		{"GOOGLE_API_KEY", "Google API Key", defaults["GOOGLE_API_KEY"]},
		{"QDRANT_HOST", "Qdrant host:port", defaults["QDRANT_HOST"]},
		{"EMDEX_NAMESPACE", "Default namespace", defaults["EMDEX_NAMESPACE"]},
		{"EMDEX_AUTH_KEY", "Auth key (empty for none)", defaults["EMDEX_AUTH_KEY"]},
		{"EMDEX_GEMINI_MODEL", "Gemini embedding model", defaults["EMDEX_GEMINI_MODEL"]},
	}

	if _, err := os.Stat(".env"); err == nil {
		fmt.Printf("  %s %s\n\n", "⚠️", ui.Yellow(".env already exists and will be overwritten."))
	}

	values := make(map[string]string)
	for _, p := range prompts {
		if p.defaultValue != "" {
			fmt.Printf("  %s %s: ", ui.Cyan(p.label), ui.Dim("["+p.defaultValue+"]"))
		} else {
			fmt.Printf("  %s: ", ui.Cyan(p.label))
		}

		var input string
		if scanner.Scan() {
			input = strings.TrimSpace(scanner.Text())
		}
		if input == "" {
			input = p.defaultValue
		}
		values[p.key] = input
	}

	var sb strings.Builder
	sb.WriteString("# Emdexer configuration — generated by emdex init\n")
	for _, p := range prompts {
		sb.WriteString(fmt.Sprintf("%s=%s\n", p.key, values[p.key]))
	}

	if err := os.WriteFile(".env", []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "  %s %s: %v\n", "❌", ui.Red("Error writing .env"), err)
		os.Exit(1)
	}
	fmt.Printf("\n  %s %s\n", "✅", ui.Green("Wrote .env — run 'emdex start' to launch services."))
	fmt.Println()
}

// cmdStart runs docker compose up -d.
func cmdStart() {
	composeFile := os.Getenv("EMDEX_COMPOSE_FILE")
	if composeFile == "" {
		composeFile = "docker-compose.yml"
	}

	args := []string{"compose", "-f", composeFile, "up", "-d"}
	cmd := exec.Command("docker", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	fmt.Printf("\n  %s %s %s\n\n", "🚀", ui.Bold("Starting emdexer services"), ui.Dim("("+composeFile+")"))
	if err := cmd.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "\n  %s %s: %v\n", "❌", ui.Red("Failed to start services"), err)
		os.Exit(1)
	}
	fmt.Printf("\n  %s %s\n\n", "✅", ui.Green("All services started. Run 'emdex status' to verify."))
}

// cmdStatus checks health endpoints of gateway and node, including worker heartbeat.
func cmdStatus() {
	gatewayURL := os.Getenv("EMDEX_GATEWAY_URL")
	if gatewayURL == "" {
		gatewayURL = "http://localhost:7700"
	}
	nodeURL := os.Getenv("EMDEX_NODE_URL")
	if nodeURL == "" {
		nodeURL = "http://localhost:8081"
	}

	fmt.Printf("\n  %s  %s\n", "📦", ui.Bold("Emdexer Service Status"))
	fmt.Printf("  %s\n\n", ui.Dim("────────────────────────────────────"))

	gwStatus, gwOK := checkHealth(gatewayURL + "/healthz/readiness")
	nodeStatus, nodeOK := checkHealth(nodeURL + "/healthz/readiness")
	workerStatus := checkWorker(nodeURL + "/healthz/worker")

	regStatus := checkRegistry(gatewayURL)

	printStatusLine("Gateway", gatewayURL, gwStatus, gwOK)
	printStatusLine("Node", nodeURL, nodeStatus, nodeOK)
	fmt.Printf("  %s  %-10s %s\n", workerStatus.emoji, ui.Bold("Worker"), workerStatus.detail)
	fmt.Printf("  %s  %-10s %s\n", regStatus.emoji, ui.Bold("Registry"), regStatus.detail)

	fmt.Printf("\n  %s\n\n", ui.Dim("────────────────────────────────────"))
}

func printStatusLine(name, url, status string, ok bool) {
	emoji := "✅"
	coloredStatus := ui.Green(status)
	if !ok {
		emoji = "❌"
		coloredStatus = ui.Red(status)
	}
	fmt.Printf("  %s  %-10s %s  %s\n", emoji, ui.Bold(name), coloredStatus, ui.Dim(url))
}

type workerResult struct {
	emoji  string
	detail string
}

func checkHealth(url string) (string, bool) {
	client := &http.Client{Timeout: 3 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return "DOWN (unreachable)", false
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusOK {
		return "UP", true
	}
	return fmt.Sprintf("UNHEALTHY (%d)", resp.StatusCode), false
}

func checkWorker(url string) workerResult {
	client := &http.Client{Timeout: 3 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return workerResult{"❌", ui.Red("DOWN") + "  " + ui.Dim("(unreachable)")}
	}
	defer resp.Body.Close()

	var result map[string]interface{}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return workerResult{"❓", ui.Yellow("UNKNOWN") + "  " + ui.Dim("(bad response)")}
	}

	status, _ := result["status"].(string)
	lastActive, _ := result["last_active"].(string)

	switch {
	case resp.StatusCode == http.StatusOK && status == "ALIVE":
		ago := ui.FormatTimeAgo(lastActive)
		return workerResult{"✅", ui.Green("ALIVE") + "  " + ui.Dim("last heartbeat "+ago)}
	case status == "STALE":
		ago := ui.FormatTimeAgo(lastActive)
		return workerResult{"⚠️", ui.Yellow("STALLED") + "  " + ui.Dim("no heartbeat for "+ago) + "\n" +
			"        " + ui.Dim("→ Worker may be stuck. Check node logs: journalctl -u emdex-node -f")}
	case status == "NO_WORKER":
		return workerResult{"⚠️", ui.Yellow("NO_WORKER") + "  " + ui.Dim("no background indexing worker registered")}
	default:
		return workerResult{"❓", ui.Yellow(status)}
	}
}

// checkRegistry verifies the gateway's node registry is reachable and parseable.
func checkRegistry(gatewayURL string) workerResult {
	authKey := os.Getenv("EMDEX_AUTH_KEY")
	if authKey == "" {
		return workerResult{"⚠️", ui.Yellow("SKIPPED") + "  " + ui.Dim("set EMDEX_AUTH_KEY to check registry")}
	}

	client := &http.Client{Timeout: 3 * time.Second}
	req, err := http.NewRequest("GET", gatewayURL+"/nodes", nil)
	if err != nil {
		return workerResult{"❌", ui.Red("ERROR") + "  " + ui.Dim(err.Error())}
	}
	req.Header.Set("Authorization", "Bearer "+authKey)

	resp, err := client.Do(req)
	if err != nil {
		return workerResult{"❌", ui.Red("DOWN") + "  " + ui.Dim("(gateway unreachable)")}
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusUnauthorized || resp.StatusCode == http.StatusForbidden {
		return workerResult{"⚠️", ui.Yellow("AUTH FAILED") + "  " + ui.Dim("check EMDEX_AUTH_KEY")}
	}
	if resp.StatusCode != http.StatusOK {
		return workerResult{"❌", ui.Red(fmt.Sprintf("HTTP %d", resp.StatusCode))}
	}

	var nodes []interface{}
	if err := json.NewDecoder(resp.Body).Decode(&nodes); err != nil {
		return workerResult{"❌", ui.Red("CORRUPT") + "  " + ui.Dim("registry response not valid JSON")}
	}

	return workerResult{"✅", ui.Green(fmt.Sprintf("OK (%d nodes)", len(nodes)))}
}

// cmdNodes queries the gateway registry and displays a colorized node table.
func cmdNodes() {
	gatewayURL := os.Getenv("EMDEX_GATEWAY_URL")
	if gatewayURL == "" {
		gatewayURL = "http://localhost:7700"
	}
	authKey := os.Getenv("EMDEX_AUTH_KEY")
	if authKey == "" {
		fmt.Fprintf(os.Stderr, "  %s %s\n", "❌", ui.Red("EMDEX_AUTH_KEY required to query nodes"))
		os.Exit(1)
	}

	client := &http.Client{Timeout: 5 * time.Second}
	req, _ := http.NewRequest("GET", gatewayURL+"/nodes", nil)
	req.Header.Set("Authorization", "Bearer "+authKey)

	resp, err := client.Do(req)
	if err != nil {
		fmt.Fprintf(os.Stderr, "  %s %s: %v\n", "❌", ui.Red("Cannot reach gateway"), err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		fmt.Fprintf(os.Stderr, "  %s HTTP %d from gateway\n", "❌", resp.StatusCode)
		os.Exit(1)
	}

	var nodes []struct {
		ID            string   `json:"id"`
		URL           string   `json:"url"`
		Namespaces    []string `json:"namespaces"`
		Protocol      string   `json:"protocol"`
		HealthStatus  string   `json:"health_status"`
		LastHeartbeat string   `json:"last_heartbeat"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&nodes); err != nil {
		fmt.Fprintf(os.Stderr, "  %s %s\n", "❌", ui.Red("Invalid response from gateway"))
		os.Exit(1)
	}

	fmt.Printf("\n  %s  %s\n", ui.Bold("📡 Registered Nodes"), ui.Dim(fmt.Sprintf("(%d total)", len(nodes))))
	fmt.Printf("  %s\n\n", ui.Dim("─────────────────────────────────────────────────────────────────────────"))

	if len(nodes) == 0 {
		fmt.Printf("  %s\n\n", ui.Dim("No nodes registered. Nodes self-register when EMDEX_GATEWAY_URL is set."))
		return
	}

	// Header
	fmt.Printf("  %-24s  %-10s  %-10s  %-20s  %s\n",
		ui.Bold("NODE ID"), ui.Bold("STATUS"), ui.Bold("PROTOCOL"), ui.Bold("NAMESPACES"), ui.Bold("LAST HEARTBEAT"))
	fmt.Printf("  %s\n", ui.Dim("─────────────────────────────────────────────────────────────────────────"))

	for _, n := range nodes {
		statusFn := ui.Green
		if n.HealthStatus != "healthy" {
			statusFn = ui.Red
		}
		ago := ui.FormatTimeAgo(n.LastHeartbeat)
		nsStr := strings.Join(n.Namespaces, ", ")
		if nsStr == "" {
			nsStr = ui.Dim("(none)")
		}

		fmt.Printf("  %-24s  %-10s  %-10s  %-20s  %s\n",
			ui.Cyan(n.ID),
			statusFn(n.HealthStatus),
			n.Protocol,
			nsStr,
			ui.Dim(ago))
	}
	fmt.Println()
}
