package main

import (
	"bufio"
	"flag"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/piotrlaczykowski/emdexer/version"
)

func main() {
	if len(os.Args) > 1 && os.Args[1][0] != '-' {
		switch os.Args[1] {
		case "init":
			cmdInit()
		case "start":
			cmdStart()
		case "status":
			cmdStatus()
		default:
			fmt.Fprintf(os.Stderr, "unknown command: %s\n", os.Args[1])
			printUsage()
			os.Exit(1)
		}
		return
	}

	showVersion := flag.Bool("version", false, "show version")
	flag.Parse()

	if *showVersion {
		fmt.Printf("emdex version %s\n", version.Version)
		os.Exit(0)
	}

	printUsage()
}

func printUsage() {
	fmt.Println("Emdexer CLI")
	fmt.Println()
	fmt.Println("Usage: emdex <command>")
	fmt.Println()
	fmt.Println("Commands:")
	fmt.Println("  init      Initialize a new emdexer project (.env)")
	fmt.Println("  start     Start emdexer services via Docker Compose")
	fmt.Println("  status    Show status of emdexer services")
	fmt.Println()
	fmt.Println("Flags:")
	fmt.Println("  --version  Show version information")
}

// cmdInit prompts for configuration values and writes a .env file.
func cmdInit() {
	scanner := bufio.NewScanner(os.Stdin)

	defaults := map[string]string{
		"GOOGLE_API_KEY":    "",
		"QDRANT_HOST":       "qdrant-1:6334",
		"EMDEX_NAMESPACE":   "default",
		"EMDEX_AUTH_KEY":    "",
		"EMDEX_GEMINI_MODEL": "gemini-embedding-2-preview",
	}

	prompts := []struct {
		key          string
		label        string
		defaultValue string
	}{
		{"GOOGLE_API_KEY", "Google API Key", defaults["GOOGLE_API_KEY"]},
		{"QDRANT_HOST", "Qdrant host:port", defaults["QDRANT_HOST"]},
		{"EMDEX_NAMESPACE", "Default namespace", defaults["EMDEX_NAMESPACE"]},
		{"EMDEX_AUTH_KEY", "Auth key (empty for none)", defaults["EMDEX_AUTH_KEY"]},
		{"EMDEX_GEMINI_MODEL", "Gemini embedding model", defaults["EMDEX_GEMINI_MODEL"]},
	}

	if _, err := os.Stat(".env"); err == nil {
		fmt.Println("Warning: .env already exists and will be overwritten.")
	}

	values := make(map[string]string)
	for _, p := range prompts {
		if p.defaultValue != "" {
			fmt.Printf("%s [%s]: ", p.label, p.defaultValue)
		} else {
			fmt.Printf("%s: ", p.label)
		}

		var input string
		if scanner.Scan() {
			input = strings.TrimSpace(scanner.Text())
		}
		if input == "" {
			input = p.defaultValue
		}
		values[p.key] = input
	}

	var sb strings.Builder
	sb.WriteString("# Emdexer configuration — generated by emdex init\n")
	for _, p := range prompts {
		sb.WriteString(fmt.Sprintf("%s=%s\n", p.key, values[p.key]))
	}

	if err := os.WriteFile(".env", []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing .env: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Wrote .env — run 'emdex start' to launch services.")
}

// cmdStart runs docker compose up -d.
func cmdStart() {
	composeFile := os.Getenv("EMDEX_COMPOSE_FILE")
	if composeFile == "" {
		composeFile = "docker-compose.yml"
	}

	args := []string{"compose", "-f", composeFile, "up", "-d"}
	cmd := exec.Command("docker", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	fmt.Printf("Starting emdexer services (%s)...\n", composeFile)
	if err := cmd.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

// cmdStatus checks health endpoints of gateway and node.
func cmdStatus() {
	gatewayURL := os.Getenv("EMDEX_GATEWAY_URL")
	if gatewayURL == "" {
		gatewayURL = "http://localhost:7700"
	}
	nodeURL := os.Getenv("EMDEX_NODE_URL")
	if nodeURL == "" {
		nodeURL = "http://localhost:8081"
	}

	fmt.Println("Emdexer Service Status")
	fmt.Println("======================")
	fmt.Printf("  Gateway (%s):  %s\n", gatewayURL, checkHealth(gatewayURL+"/healthz/readiness"))
	fmt.Printf("  Node    (%s):  %s\n", nodeURL, checkHealth(nodeURL+"/healthz/readiness"))
}

func checkHealth(url string) string {
	client := &http.Client{Timeout: 3 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return "DOWN"
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusOK {
		return "UP"
	}
	return fmt.Sprintf("UNHEALTHY (%d)", resp.StatusCode)
}
