apiVersion: v1
kind: Secret
metadata:
  name: {{ include "emdexer-gateway.fullname" . }}-secret
type: Opaque
data:
  google-api-key: {{ .Values.secret.googleApiKey | b64enc | quote }}
  authKey: {{ .Values.secret.authKey | b64enc | quote }}
  {{- if .Values.secret.rerankToken }}
  rerankToken: {{ .Values.secret.rerankToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.openaiApiKey }}
  openai-api-key: {{ .Values.secret.openaiApiKey | b64enc | quote }}
  {{- end }}
